version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'backend-db'
    environment: 
      - MONGO_INITDB_DATABASE=BUDGET-DB
      - MONGO_INITDB_USERNAME=dbadmin
      - MONGO_INITDB_PASSORD=secret
    volumes:
      - ./mongo-volume:/data/db
    ports: 
      - '27017-27019:27017-27019'